name: dartdoc_viewer
description: Dart API Reference
dependencies:
  barback: any
  browser: any
  polymer:
    path: /Users/alanknight/dart-git/dart/pkg/polymer
  polymer_expressions:
    path: /Users/alanknight/dart-git/dart/pkg/polymer_expressions
  yaml: any
