name: dartdoc_viewer
description: Dart API Reference
dependencies:
  barback: any
  browser: any
  polymer: any
#    path: /Users/alanknight/dart-git/dart/pkg/polymer
  polymer_expressions: any
#    path: /Users/alanknight/dart-git/dart/pkg/polymer_expressions
  yaml: any
