name: dartdoc_viewer
description: Dart API Reference
dependencies:
  polymer: any
  polymer_expressions: any
  yaml: any
transformers:
- polymer:
    entry_points: web/index.html
dev_dependencies:
  unittest: any
  barback: any
dependency_overrides:
  polymer: { path: /mnt/code/dart/dart/pkg/polymer }
  observe: { path: /mnt/code/dart/dart/pkg/observe }
  shadow_dom: { path: /mnt/code/dart/dart/pkg/shadow_dom }
  html5lib: { path: /mnt/code/dart/dart/pkg/third_party/html5lib }
  barback: { path: /mnt/code/dart/dart/pkg/barback }
